
POST https://render-test-yqkl.onrender.com/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###
POST http://localhost:3000/login/register
Content-Type: application/json

{
  "username": "aorko",
  "password": "aorko"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

# .............................................................................
###
POST http://localhost:8080/register
Content-Type: application/json

{
  "email": "test1@gmail.com"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "testi@gmail.com" 
}

###
GET http://localhost:8080/movies?category=action